name: CI/CD for Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
          MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: copy .env
        run: |
          cp .env.example .env

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Install NPM dependencies
        run: |
          npm install
      - name: clear cache
        run:
          php artisan optimize:clear

      - name: Set environment variables
        run: |
            echo "APP_ENV=local" >> .env
            echo "DB_CONNECTION=mysql" >> .env
            echo "DB_HOST=db" >> .env
            echo "DB_PORT=3306" >> .env
            echo "DB_DATABASE=laravel" >> .env
            echo "DB_USERNAME=laravel" >> .env
            echo "DB_PASSWORD=laravel" >> .env
      - name: Wait for MySQL to start
        run: |
          until nc -z -v -w30 db 3306; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run tests
        run: |
          php artisan migrate --force

      - name: Build assets
        run: |
          npm run dev

      - name: Deploy to server (optional)
        run: |
          ssh user@your-server 'cd /path/to/your/app && git pull && php artisan migrate'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
