name: CI/CD for Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Install NPM dependencies
        run: |
          npm install
      - name: clear cache
        run:
          php artisan optimize:clear
      - name: Run tests
        run: |
          echo "APP_ENV=local" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_KEY=$(php -r 'echo base64_encode(random_bytes(32));')" >> .env
          php artisan migrate --env=local --force

      - name: Build assets
        run: |
          npm run dev

      - name: Deploy to server (optional)
        run: |
          ssh user@your-server 'cd /path/to/your/app && git pull && php artisan migrate'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
