name: CI/CD for Laravel

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'dev' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install --frozen-lockfile
      - run: npm run build

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ github.ref == 'refs/heads/main' && '/var/www/ci-cd' || '/var/www/ci-cd-dev' }}
      - name: Debug GitHub Environment Variables
        run: printenv | grep -E 'APP_NAME|DB_HOST|MAIL_HOST'
      - name: Setup Environment and Run Migrations
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: APP_NAME,APP_ENV,APP_KEY,APP_DEBUG,APP_URL,LOG_CHANNEL,LOG_DEPRECATIONS_CHANNEL,LOG_LEVEL,DB_CONNECTION,DB_HOST,DB_PORT,DB_DATABASE,DB_USERNAME,DB_PASSWORD,REDIS_HOST,MAIL_MAILER,BROADCAST_DRIVER,CACHE_DRIVER,FILESYSTEM_DISK,QUEUE_CONNECTION,SESSION_DRIVER,SESSION_LIFETIME,MEMCACHED_HOST,REDIS_PASSWORD,REDIS_PORT,MAIL_HOST,MAIL_PORT,MAIL_USERNAME,MAIL_PASSWORD,MAIL_ENCRYPTION,MAIL_FROM_ADDRESS,MAIL_FROM_NAME,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION,AWS_BUCKET,AWS_USE_PATH_STYLE_ENDPOINT,PUSHER_APP_ID,PUSHER_APP_KEY,PUSHER_APP_SECRET,PUSHER_HOST,PUSHER_PORT,PUSHER_SCHEME,PUSHER_APP_CLUSTER,VITE_PUSHER_APP_KEY,VITE_PUSHER_HOST,VITE_PUSHER_PORT,VITE_PUSHER_SCHEME,VITE_PUSHER_APP_CLUSTER
          script: |
            TARGET_PATH=${{ github.ref == 'refs/heads/main' && '/var/www/ci-cd' || '/var/www/ci-cd-dev' }}
            cd $TARGET_PATH

            # Tạo file .env từ template
            envsubst < .env.example-ci-cd > .env
            echo "✅ .env file generated successfully!"

            # Thiết lập quyền
            chmod -R 775 storage bootstrap/cache

            # Chạy các lệnh tối ưu hóa và migrations
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Khởi động lại dịch vụ
            sudo systemctl restart nginx
