name: CI/CD for Laravel

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install --frozen-lockfile
      - run: npm run build
      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ github.ref == 'refs/heads/main' && '/var/www/ci-cd' || '/var/www/ci-cd-dev' }}
      - name: Debug GitHub Variables
        run: |
          echo "APP_NAME=${{ vars.APP_NAME }}"
          echo "APP_ENV=${{ vars.APP_ENV }}"
          echo "APP_URL=${{ vars.APP_URL }}"
          echo "APP_KEY=${{ vars.APP_KEY }}"
      - name: Setup Environment and Run Migrations
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            TARGET_PATH=${{ github.ref == 'refs/heads/main' && '/var/www/ci-cd' || '/var/www/ci-cd-dev' }}
            cd $TARGET_PATH
            cp .env.example-ci-cd .env
            sed -i "s#\${APP_NAME}#${{ vars.APP_NAME }}#g" .env
            sed -i "s#\${APP_ENV}#${{ vars.APP_ENV }}#g" .env
            sed -i "s#\${APP_URL}#${{ vars.APP_URL }}#g" .env
            sed -i "s#\${APP_KEY}#${{ secrets.APP_KEY }}#g" .env
            sed -i "s#\${LOG_CHANNEL}#${{ vars.LOG_CHANNEL }}#g" .env
            sed -i "s#\${LOG_DEPRECATIONS_CHANNEL}#${{ vars.LOG_DEPRECATIONS_CHANNEL }}#g" .env
            sed -i "s#\${LOG_LEVEL}#${{ vars.LOG_LEVEL }}#g" .env

            sed -i "s#\${DB_CONNECTION}#${{ vars.DB_CONNECTION }}#g" .env
            sed -i "s#\${DB_HOST}#${{ vars.DB_HOST }}#g" .env
            sed -i "s#\${DB_PORT}#${{ vars.DB_PORT }}#g" .env
            sed -i "s#\${DB_DATABASE}#${{ vars.DB_DATABASE }}#g" .env
            sed -i "s#\${DB_USERNAME}#${{ vars.DB_USERNAME }}#g" .env
            sed -i "s#\${DB_PASSWORD}#${{ secrets.DB_PASSWORD }}#g" .env

            sed -i "s#\${BROADCAST_DRIVER}#${{ vars.BROADCAST_DRIVER }}#g" .env
            sed -i "s#\${CACHE_DRIVER}#${{ vars.CACHE_DRIVER }}#g" .env
            sed -i "s#\${FILESYSTEM_DISK}#${{ vars.FILESYSTEM_DISK }}#g" .env
            sed -i "s#\${QUEUE_CONNECTION}#${{ vars.QUEUE_CONNECTION }}#g" .env
            sed -i "s#\${SESSION_DRIVER}#${{ vars.SESSION_DRIVER }}#g" .env
            sed -i "s#\${SESSION_LIFETIME}#${{ vars.SESSION_LIFETIME }}#g" .env


            echo "✅ .env file generated successfully!"
            chmod -R 775 storage bootstrap/cache

            # Chạy các lệnh tối ưu hóa và migrations
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Khởi động lại dịch vụ
            sudo systemctl restart nginx
