name: CI/CD for Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Install NPM dependencies
        run: |
          npm install
      - name: clear cache
        run:
          php artisan optimize:clear
      - name: Set environment variables
        run: |
            echo "DB_CONNECTION=mysql" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=3306" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Run tests
        run: |
          php artisan migrate --force

      - name: Build assets
        run: |
          npm run dev

      - name: Deploy to server (optional)
        run: |
          ssh user@your-server 'cd /path/to/your/app && git pull && php artisan migrate'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
